import background1 from './background1/background1.png';
import coffee1 from './coffee1/coffee.png';
import coffee2 from './coffee2/coffee2.png';
import coffee3 from './coffee3/coffee3.png';
import coffee4 from './coffee4/coffee4.png';
import coffee5 from './coffee5/coffee5.png';
import banner from './banner/banner.png';
import map from './map/map.png';
import route from './rute/rute.png';
import deliveryBoy from './deliveryBoy/deliveryBoy.png';
import profileImage from './profile/profile.png';
export { background1, coffee1, coffee2, coffee3, coffee4, coffee5, banner, map, route, deliveryBoy, profileImage };
